import React,{useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {Page,Card,Stat,Badge} from "../components";
import {history,demoOverview,procurementOverview,currentUser} from "../services/api";
import {Activity,Database,ShieldCheck,Network,ArrowUpRight,BriefcaseBusiness,FilePlus2,SearchCheck,Users,ClipboardCheck,Landmark,Factory,Clock3} from "lucide-react";
import {RevealGroup} from "../components/chrome";

const ROLE_DASH={
 ORGANIZATION_ADMIN:{eyebrow:"ORGANISATION CONTROL",title:"Organisation procurement dashboard",desc:"Create requirements, monitor your tender pipeline and move approved procurements to publication.",actions:["Create tender","/procurement"],metrics:["draft","review","published","bids"]},
 PROCUREMENT_OFFICER:{eyebrow:"PROCUREMENT OPERATIONS",title:"Procurement officer dashboard",desc:"Manage tender authoring, compliance gates, supplier bids and evaluation from one workspace.",actions:["Open procurement hub","/procurement"],metrics:["draft","review","published","bids"]},
 GOVERNMENT_REVIEWER:{eyebrow:"GOVERNMENT REVIEW",title:"Government review dashboard",desc:"Review procurement cases and supplier submissions with evidence and evaluation context.",actions:["Review procurements","/procurement"],metrics:["published","evaluation","awarded","bids"]},
 STANDARDS_OFFICER:{eyebrow:"STANDARDS INTELLIGENCE",title:"Standards officer dashboard",desc:"Validate standards references, evidence and version relationships supporting procurement decisions.",actions:["Open standards","/standards"],metrics:["standards","evidence","relationships","review"]},
 COMPLIANCE_OFFICER:{eyebrow:"COMPLIANCE CONTROL",title:"Compliance dashboard",desc:"Control the publication gate and return incomplete tenders before they become public opportunities.",actions:["Open compliance queue","/procurement"],metrics:["review","draft","published","gaps"]},
 VENDOR:{eyebrow:"SUPPLIER WORKSPACE",title:"Supplier opportunity dashboard",desc:"Find published government tenders, review requirements and submit bids for your organisation.",actions:["Browse tenders","/procurement"],metrics:["published","bids","submitted","awarded"]},
 AUDITOR:{eyebrow:"AUDIT & TRACEABILITY",title:"Procurement audit dashboard",desc:"Inspect lifecycle events and trace tender activity from creation through award.",actions:["Open audit hub","/procurement"],metrics:["events","published","awarded","bids"]},
 ADMIN:{eyebrow:"PLATFORM ADMINISTRATION",title:"NORMEX platform dashboard",desc:"Platform-wide synthetic visibility across procurement, standards, evidence and audit activity.",actions:["Open procurement hub","/procurement"],metrics:["published","evaluation","awarded","bids"]},
};

const LABELS={draft:"Draft tenders",review:"Compliance review",published:"Published tenders",bids:"Supplier bids",evaluation:"In evaluation",awarded:"Awarded",standards:"Standards indexed",evidence:"Evidence records",relationships:"Graph relationships",gaps:"Open gaps",submitted:"My submissions",events:"Audit events"};

export default function Dashboard(){
 const user=currentUser(); const cfg=ROLE_DASH[user?.role]||ROLE_DASH.ADMIN; const [h,setH]=useState([]),[o,setO]=useState(null),[p,setP]=useState(null);
 useEffect(()=>{history().then(setH).catch(()=>{});demoOverview().then(setO).catch(()=>{});procurementOverview().then(setP).catch(()=>{})},[]);
 const c=p?.counts||{}; const demo={standards:o?.standards??"—",evidence:o?.evidence??"—",relationships:o?.relationships??"—",gaps:o?.open_gaps??14,events:h.length,published:c.published||0,evaluation:c.evaluation||0,awarded:c.awarded||0,bids:c.bids||0,draft:c.draft||0,review:c.review||0,submitted:0};
 return <Page eyebrow={cfg.eyebrow} title={cfg.title} description={cfg.desc} actions={<Link className="primary" to={cfg.actions[1]}>{cfg.actions[0]}</Link>}>
   <div className="synthetic-banner"><Database size={16}/><b>Role-scoped synthetic workspace</b><span>{user?.organization||"NORMEX Demo Authority"} · {user?.role?.replaceAll("_"," ")}</span></div>
   <RevealGroup className="statgrid" stagger={55}>{cfg.metrics.map(k=><Stat key={k} label={LABELS[k]||k} value={demo[k]??0} sub={metricSub(k,user?.role)}/>)}</RevealGroup>
   <RoleActions role={user?.role}/>
   <div className="two-col" style={{marginTop:18}}><Card><div className="row between"><h2>Procurement lifecycle</h2><Link className="textlink" to="/procurement">Open hub <ArrowUpRight size={13}/></Link></div><Lifecycle role={user?.role} counts={c}/></Card><Card><h2>Workspace focus</h2><Focus role={user?.role}/></Card></div>
   {!["VENDOR","AUDITOR"].includes(user?.role)&&<div className="two-col" style={{marginTop:18}}><Card><div className="row between"><h2>Recent analyses</h2><Link className="textlink" to="/history">View history <ArrowUpRight size={13}/></Link></div>{h.length?h.slice(0,5).map(x=><div className="listrow" key={x.id}><div><b>{x.product||"Procurement case"}</b><small>{x.domain||"General"} · {new Date(x.created_at).toLocaleString()}</small></div><Badge tone="good">SAVED</Badge></div>):<div className="empty">No analyses yet.</div>}</Card><RiskCard role={user?.role}/></div>}
 </Page>
}

function metricSub(k,role){if(k==="bids")return role==="VENDOR"?"Opportunities submitted":"Across visible tenders";if(k==="published")return role==="VENDOR"?"Available opportunities":"Public opportunities";if(k==="review")return "Waiting for compliance";return "Current workspace view"}
function RoleActions({role}){const actions={ORGANIZATION_ADMIN:[["/procurement","Create tender",FilePlus2],["/tender-linter","Lint requirements",SearchCheck]],PROCUREMENT_OFFICER:[["/procurement","Manage tenders",BriefcaseBusiness],["/evaluation","Evaluate bids",ClipboardCheck]],GOVERNMENT_REVIEWER:[["/procurement","Review bids",ClipboardCheck],["/evidence","Inspect evidence",Database]],STANDARDS_OFFICER:[["/standards","Standards library",SearchCheck],["/graph","Knowledge graph",Network]],COMPLIANCE_OFFICER:[["/procurement","Review queue",ShieldCheck],["/compliance","Compliance workspace",ClipboardCheck]],VENDOR:[["/procurement","Browse tenders",BriefcaseBusiness]],AUDITOR:[["/procurement","Audit trail",Clock3],["/reports","Reports",Database]],ADMIN:[["/procurement","Procurement",BriefcaseBusiness],["/standards","Standards",SearchCheck]]};return <div className="two-col" style={{marginTop:18}}>{(actions[role]||actions.ADMIN).map(([to,label,Icon])=><Link className="card" key={to} to={to} style={{textDecoration:"none"}}><div className="row between"><div><span className="eyebrow">QUICK ACTION</span><h2 style={{margin:"8px 0 0"}}>{label}</h2></div><Icon size={24}/></div></Link>)}</div>}
function Lifecycle({role,counts}){const steps=role==="VENDOR"?["Published","Read requirements","Submit bid","Evaluation","Award"]:role==="COMPLIANCE_OFFICER"?["Draft","NORMEX analysis","Compliance review","Approved","Published"]:["Requirement","Draft","NORMEX analysis","Compliance","Published","Bidding","Evaluation","Award"];return <div className="workflow-strip" style={{marginTop:12}}>{steps.map((s,i)=><div key={s}><span>{String(i+1).padStart(2,"0")}</span>{s}{i<steps.length-1&&<ArrowUpRight size={13}/>}</div>)}</div>}
function Focus({role}){const text={ORGANIZATION_ADMIN:["Create the procurement requirement","Monitor only your organisation's tenders","Publish only after compliance approval"],PROCUREMENT_OFFICER:["Author and analyse tenders","Close bidding and evaluate suppliers","Maintain procurement traceability"],GOVERNMENT_REVIEWER:["Review submitted bids","Inspect evidence and scores","Participate in award decision"],STANDARDS_OFFICER:["Validate BIS/standards references","Check versions and evidence","Support procurement reviewers"],COMPLIANCE_OFFICER:["Review requirement gaps","Approve or return tenders","Control the publication gate"],VENDOR:["See only published tenders","Submit one bid per organisation","Track evaluation / award status"],AUDITOR:["Read lifecycle events","Trace actors and entities","Verify audit chronology"],ADMIN:["Platform-wide visibility","Manage synthetic environment","Inspect audit and procurement"]};return <>{(text[role]||text.ADMIN).map((x,i)=><div className="checkitem" key={x}><span>{i+1}</span><b>{x}</b></div>)}</>}
function RiskCard({role}){return <Card><div className="section-mini"><div><span className="muted">CONTROL SIGNALS</span><strong>{role==="COMPLIANCE_OFFICER"?"Publication gate":"Procurement health"}</strong></div><ShieldCheck size={24}/></div>{["Completeness","Standards coverage","Evidence traceability","Compliance","Auditability"].map((x,i)=><div className="riskline" key={x}><span>{x}</span><div className="bar"><i style={{width:`${[82,91,88,76,96][i]}%`}}/></div><small>{["Good","Strong","Good","Review","Strong"][i]}</small></div>)}</Card>}
